name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
             git push https://yashDhiman2004:$HF_TOKEN@huggingface.co/spaces/yashDhiman2004/anemia_sense main


